### PR TITLE
Add Session.GetLink(String) method for interworking with Web API

### PR DESCRIPTION
**Pull request by brianavid**
Changes to add Session.GetLink(String) to allow inter-working with Web API

### CODE REVIEW

**Comment by Alxandr** [comment]
Please run the release script so that the version bump is included in the PR.

**Comment by brianavid** [comment]
I think I have done it - the release script certainly bumped the version number. But this is my first attempt at a pull request, so I may have missed something!

**Comment by Alxandr** [comment]
Yes, your latest commit updated the build number. I'll merge this. If you want it on nuget, send me the latest generated nupkeg.

**Comment by brianavid** [comment]
Attached are the nuget package(s) from the build of my fork. Thanks for
doing this - I feel more comfortable with all source updates in the master
hierarchy.

Brian

**Comment by Alxandr** [comment]
@brianavid email attachments are removed by github afaik. You'll have to mail me personally.

**Pull request merged**
