### PR TITLE
Updated NuGet dependencies and fixed occasional Exception

### PR DESCRIPTION
**Pull request by NeoLegends**
Occasionally, SpotiFire will thrown an `InvalidOperationException` while trying to set the login `TaskCompletionSource`'s result. The call to `SetResult` was replaced with `TrySetResult` to prevent the errors.

Also updated the outdated NuGet dependencies. (This is why there are so many changes, there were lots of changes in the XML doc. I suggest .gitignoring the `packages`-Folder and removing all of its traces via BFG repo cleaner to reduce the size of the repo)

### CODE REVIEW

**Comment by NeoLegends** [comment]
I'll mail you the new NuGet package files, if required. :)

**Comment by Alxandr** [comment]
So, as you've probably realized, I'm working on a bunch of projects that isn't SpotiFire ATM, and at the same time also trying to balance studies. So if you'd like, I can just add you as collaborator, and give you write history to the repository (and nuget.org package). It would allow you to develop along with your needs. I still have plans for SpotiFire, I know where I want to take it, I just have a lot of stuff with higher priorities, so getting another developer who wants to wotk on it (at least for the time being, while you develop with it) would just be great :).

**Comment by NeoLegends** [comment]
Yes, why not. :)

I'd need to know the direction you want to take it to, though.

**Comment by NeoLegends** [comment]
Wait! Don't merge. It seems like changing SetResult to TrySetResult causes a deadlock, for whatever reason. (at least within my application)

Don't merge until that is fixed, please. :)

**Comment by Alxandr** [comment]
Could you join me at https://gitter.im/Alxandr/SpotiFire at some point?

**Pull request closed without merging**
